### ISSUE TITLE
kube-startup-cpu-boost-mutating-webhook-configuration is intercepting resources in the kube-system namespace

### ISSUE THREAD

**Issue by pslattery-wyn** [google/kube-startup-cpu-boost#27]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do
not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Steps to Reproduce

Install on a GKE 1.29.x cluster with:
```
kubectl apply -f https://github.com/google/kube-startup-cpu-boost/releases/download/v0.4.0/manifests.yaml
```
Add a sample StartupCPUBoost manifest
Dehydrate cluster by scaling all deployments/statefulsets to zero, scale all node pools to zero.
Then scale the node pools back up and the deployments/statefulsets back up.

### Expected Behavior

All pods should startup again.

### Actual Behavior

kube-startup-cpu-boost-mutating-webhook-configuration is intercepting resources in the kube-system namespace. No pods can start.

* #0000

**Comment by mikouaj** [comment]
Hi @pslattery-wyn, thank you for opening this bug I will look into it.
