### ISSUE TITLE
Global CPUBoost

### ISSUE THREAD

**Issue by camaeel** [google/kube-startup-cpu-boost#55]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do
not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Current CPUBoost is namespace scoped. It would be great if I could set a global CPUBoost for pods matching some label selector (for example: pod-technology=java) and then set some default startup increase so migration of multiple applications should be easy.

### References

* #0000

**Comment by mikouaj** [comment]
Hi @camaeel, thank you for creating this feature request.
I'm keen to understand the use case and requirements for the cluster wide Startup CPU Boost. You have mentioned migration, can you please elaborate a bit on this ? What is being migrated, from where and to where ? 

One of the considerations would be to priority of a cluster wide Startup CPU Boost vs namespaced ones, which is related to #56 . What is your view on that in a context of this use case?

**Comment by camaeel** [comment]
We have pretty big environments (few hundreds of deployments ~ few hundreds of helm releases in one cluster) and applying for all of them new resource is impossible. 

Our current solution is to use https://github.com/dbschenker/thundering-herd-scheduler which is not perfect but limits number of pods starting in parallel on a node. 

I'm thinking about moving from old solution there are few approaches:
* we can introduce new version of base helm chart and let the migration be done gradually when new versions of applications with new versions of helm chart are deployed - this doesn't require any additional feature but will take some time.
* if I could set up some general CPUBoost for example per namespace or per cluster I could perform the migration quickly by redeploying all namespaces or deploying cluster-wide CPUboost. Let's assume I would increasse CPU limit to 2 by default for every pod in namespace/cluster. But in some rare cases of super-heavy applications it might be not enough and then application owner could set a different value (let's say 4). This would save a lot of effort.

**Comment by mikouaj** [comment]
Thanks @camaeel I've opened #61 to track this feature request.
We plan to close the MVP in September and discuss this for the next version.

**Comment by camaeel** [comment]
Great, thanx.
