### ISSUE TITLE
Multiple StartupCPUBoosts targeting same pod

### ISSUE THREAD

**Issue by camaeel** [google/kube-startup-cpu-boost#56]
What will be the behaviour of this tool if multiple StartupCPUBoost resources target the same pod? For example I could set a namespace default StartupCPUBoost without any selectors and the for some of deployments I would need to set it to bigger increases.

**Comment by mikouaj** [comment]
Hi @camaeel,
Thank you for rising this issue. Currently there is no logic to handle multiple StartupCPUBoosts targeting same PODs - for a given pod the first matching boost is used. Having overlapping StartupCPUBoosts is undesired situation IMO and I would avoid it via validation. 
For a namespace wide StartupCPUBoost I would introduce separate resource with an ordering like: StartupCPUBoost --no match -> NamespaceStartupCPUBoost --nomatch -> ClusterStartupCPUBoost (as requested in #55 )

An alternative approach would be to allow overlapping StartupCPUBoost objects and introduce some sort of priority setting but this introduced complexity and I don't clearly see any use case for this. Feel free to share your opinion as well.

**Comment by camaeel** [comment]
Thank you for clarification.
